services:
  qdrant-script:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qdrant-script-container
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}          # Claves API o variables de entorno requeridas
      - QDRANT_URL=${QDRANT_URL}                  # URL de la instancia de Qdrant
      - OTHER_ENV_VAR=${OTHER_ENV_VAR}            # Otras variables necesarias
    volumes:
      - ./data:/app/data                          # Montar un volumen para persistir datos si es necesario
    ports:
      - "8000:8000"                               # Expone puertos si el script tiene un servidor
    depends_on:
      - qdrant-db                                 # Si dependes de otros servicios
    command: python qdrant.py                     # Comando para ejecutar el script cuando se levante el contenedor

  qdrant-db:
    image: qdrant/qdrant:v0.9.0                    # Imagen de Qdrant, asegúrate de utilizar la versión correcta
    container_name: qdrant-db-container
    environment:
      - QDRANT_LOG_LEVEL=info
    ports:
      - "6333:6333"                                # Puerto predeterminado para Qdrant
    volumes:
      - qdrant_storage:/qdrant/storage             # Volumen para almacenamiento persistente de datos

volumes:
  qdrant_storage:
