services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
  
  script_runner:
    build:
      context: .
    container_name: script_runner
    depends_on:
      - qdrant
    command: ["python", "qdrant.py"]  
